# -*- coding: utf-8 -*-
"""Data Transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oBHauO-xF_nbhZvJOCuBNH7Zn4rcE1v7
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder


# Load the dataset
df = pd.read_csv('pandas data.csv', encoding='latin1')

# Check initial data
print("✅ Original Data Info:")
print(df.info())
print(df.head())

# Clean column names
df.columns = [c.strip().lower().replace(" ", "_") for c in df.columns]
print("✅ Cleaned column names:")
print(df.columns)

# Identify numeric and categorical columns
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(include='object').columns.tolist()

# Fill missing values
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

for col in categorical_cols:
    df[col] = df[col].str.lower().str.strip()  # normalize
    df[col] = df[col].fillna(df[col].mode()[0])

print("✅ Missing values handled")

df['colour'] = df['colour'].replace({
    'clourless': 'colourless',
    'faint brown': 'faint brown',  # keep as is
    'colourless':'colourless'
})

print("✅ Corrected categorical typos")
print(df['colour'].unique())

print("Numeric columns:", numeric_cols)
print("Categorical columns:", categorical_cols)

scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("✅ Numeric columns scaled")
print(df[numeric_cols].head())

encoder = OneHotEncoder(sparse_output=False, drop='first')
encoded = pd.DataFrame(
    encoder.fit_transform(df[['colour']]),
    columns=encoder.get_feature_names_out(['colour'])
)

# Drop original and add encoded columns
df = pd.concat([df.drop(['colour'], axis=1), encoded], axis=1)
print("✅ Categorical columns encoded")
print(df.head())

df['tds_ec_ratio'] = df['tds'] / df['ec']
print("✅ Feature engineering done")
print(df[['tds', 'ec', 'tds_ec_ratio']].head())

# Check the actual columns
print(df.columns.tolist())

# Numeric columns + new feature
all_numeric = numeric_cols + ['tds_ec_ratio']
df[all_numeric] = df[all_numeric].astype('float32')

# One-hot encoded columns
encoded_cols = encoder.get_feature_names_out(['colour']).tolist()
df[encoded_cols] = df[encoded_cols].astype('float32')

print("✅ Data type conversion done")
print(df.dtypes)

print("✅ Final dataset info:")
print(df.info())
print(df.head())