# -*- coding: utf-8 -*-
"""Hybrid Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nEGLzwFOEK3wKvXR2uw8Mux730fdcsUl
"""

# @title 🚀 COMPLETE HYBRID DHA CHATBOT - STANDALONE
# Copy ALL of this code into ONE Colab cell and run it

import torch
import re
from transformers import pipeline

print("="*70)
print("🏡 DHA LAHORE PROPERTY CHATBOT - HYBRID VERSION")
print("="*70)
print("This chatbot ALWAYS works - no training needed!")

class HybridDHAChatbot:
    """Complete hybrid chatbot - works immediately"""

    def __init__(self):
        print("\n🤖 Loading Hybrid DHA Chatbot...")

        # Load pre-trained model (no training needed)
        self.generator = pipeline(
            "text-generation",
            model="microsoft/DialoGPT-small",
            tokenizer="microsoft/DialoGPT-small",
            device=0 if torch.cuda.is_available() else -1
        )

        # Rule-based responses for ACCURACY
        self.rules = {
            # ========== GREETINGS ==========
            r'hello|hi|hey|salam': "Hello! I'm your DHA property assistant. How can I help you today?",
            r'good morning': "Good morning! How can I assist you with DHA properties?",
            r'good afternoon': "Good afternoon! What property information do you need?",
            r'good evening': "Good evening! I'm here to help with DHA property queries.",
            r'how are you': "I'm doing well, thank you! How can I help you with DHA properties?",

            # ========== EXIT COMMANDS ==========
            r'bye|goodbye': "Goodbye! Thank you for using our DHA property service. 🏡",
            r'exit|quit': "Session ended. Thank you for visiting!",
            r'see you': "See you later! Take care.",
            r'thanks,? bye': "You're welcome! Goodbye and have a great day.",

            # ========== THANKS ==========
            r'thank you|thanks': "You're welcome! Let me know if you need more information.",
            r'thank you very much': "You're very welcome! Happy to help.",

            # ========== HELP ==========
            r'help|what can you do': "I can help you with:\n• Property prices\n• Plot sizes (5 Marla, 10 Marla, etc.)\n• DHA phases (1-10)\n• Property availability\nWhat do you need?",
            r'what help': "I provide information about DHA Lahore properties including prices, locations, and availability.",

            # ========== PROPERTY PRICES ==========
            r'price of 5 marla': "5 Marla plots in DHA typically cost PKR 3.5 to 4.5 crore, depending on the phase.",
            r'price of 10 marla': "10 Marla plots are usually priced between PKR 8 to 10 crore in DHA.",
            r'price of 1 kanal': "1 Kanal plots range from PKR 15 to 20 crore based on location and phase.",
            r'how much.*5 marla': "For 5 Marla plots, expect to pay around PKR 3.5 to 4.5 crore.",
            r'how much.*10 marla': "10 Marla plots cost approximately PKR 8 to 10 crore.",
            r'cost of plot': "Plot prices vary by size:\n• 5 Marla: PKR 3.5-4.5 crore\n• 10 Marla: PKR 8-10 crore\n• 1 Kanal: PKR 15-20 crore",

            # ========== PLOT SIZES ==========
            r'5 marla plot': "5 Marla plots are available in all DHA phases. They are popular for residential construction.",
            r'10 marla plot': "10 Marla plots offer more space and are good for larger homes. Available in most phases.",
            r'1 kanal plot': "1 Kanal plots are premium properties, ideal for luxury homes. Limited availability.",

            # ========== DHA PHASES ==========
            r'phase 8': "Phase 8 is well-developed with good infrastructure. Prices are moderate to high.",
            r'phase 6': "Phase 6 is a premium phase with excellent amenities. Prices are higher here.",
            r'phase 5': "Phase 5 is established with good facilities. Offers good value for money.",
            r'phase 7': "Phase 7 has both residential and commercial properties. Good for investment.",
            r'phase [1-4]': "Phases 1-4 are older, fully developed areas with established communities.",
            r'phase [9-10]': "Phases 9-10 are newer developments with modern planning.",

            # ========== PROPERTY TYPES ==========
            r'commercial plot': "Commercial plots are available in Phase 7, 8, and 6. Ideal for business use.",
            r'residential plot': "Residential plots are available in all phases. Best for home construction.",
            r'house for sale': "Houses are available in various sizes. Prices start from PKR 10 crore.",

            # ========== AVAILABILITY ==========
            r'available propert': "Properties are available in all DHA phases. What size and phase are you interested in?",
            r'is.*available': "Yes, properties are available. Could you specify the size and phase?",
            r'any plot': "Yes, plots are available. We have 5 Marla, 10 Marla, and 1 Kanal sizes.",

            # ========== GENERAL PROPERTY QUESTIONS ==========
            r'what propert': "We have residential plots, commercial plots, and houses in DHA Lahore.",
            r'tell me about dha': "DHA (Defence Housing Authority) Lahore has 10 phases with residential and commercial properties.",
            r'dha lahore': "DHA Lahore is a premium residential area with excellent infrastructure and security.",

            # ========== COMPARISONS ==========
            r'phase 6 vs phase 8': "Phase 6 is more established and expensive. Phase 8 is newer with good growth potential.",
            r'5 marla vs 10 marla': "5 Marla is smaller and more affordable. 10 Marla offers more space at higher cost.",

            # ========== LOCATION ==========
            r'where is dha': "DHA Lahore is located in Lahore, Pakistan. It has multiple phases across the city.",
            r'location': "DHA properties are located in Lahore, with different phases in various parts of the city.",

            # ========== INVESTMENT ==========
            r'investment|good investment': "DHA properties are generally good investments due to consistent value appreciation.",
            r'best phase for investment': "Phase 8 and Phase 6 are good for investment due to growth potential.",
        }

        print("✅ Hybrid chatbot ready!")
        print("   • Rule-based responses for accuracy")
        print("   • AI-powered for complex questions")
        print("   • No training required")

    def get_rule_response(self, query: str) -> str:
        """Check if query matches any rules (for ACCURACY)"""
        query_lower = query.lower().strip()

        # Special case: empty query
        if not query_lower:
            return "Please ask a question about DHA properties."

        # Check all rules
        for pattern, response in self.rules.items():
            if re.search(pattern, query_lower):
                return response

        return None

    def generate_response(self, query: str) -> str:
        """Generate response using hybrid approach"""
        # 1. First try rule-based (ACCURATE)
        rule_response = self.get_rule_response(query)
        if rule_response:
            return rule_response

        # 2. Use AI for other queries
        prompt = f"""You are a helpful DHA Lahore property assistant.

Question: {query}

Provide a clear, accurate answer about DHA properties.
Keep it to 2-3 sentences maximum.

Answer:"""

        try:
            response = self.generator(
                prompt,
                max_length=120,
                num_return_sequences=1,
                temperature=0.3,  # Low temperature for accuracy
                do_sample=True,
                top_p=0.9,
                repetition_penalty=1.2
            )[0]['generated_text']

            # Extract just the answer part
            if "Answer:" in response:
                response = response.split("Answer:")[-1].strip()

            # Clean up
            response = response.split("\n")[0].strip()

            # Ensure proper formatting
            if response and not response.endswith(('.', '!', '?')):
                response = response + '.'
            if response and len(response) > 1:
                response = response[0].upper() + response[1:]

            return response

        except Exception as e:
            return "I can help with DHA property information. Please ask about prices, phases, or availability."

    def quick_test(self):
        """Quick test of the chatbot"""
        print("\n" + "="*60)
        print("🧪 QUICK TEST")
        print("="*60)

        test_cases = [
            ("Hello", "greeting"),
            ("Price of 5 Marla plot", "price"),
            ("Phase 8 properties", "phase"),
            ("Commercial plots", "commercial"),
            ("Bye", "exit"),
        ]

        for query, category in test_cases:
            print(f"\n👤 [{category.upper()}] {query}")
            print(f"🤖 {self.generate_response(query)}")

    def interactive_chat(self):
        """Main chat interface"""
        print("\n" + "="*70)
        print("🏡 DHA LAHORE - PROPERTY EXPERT CHAT")
        print("="*70)
        print("\nI'm your DHA property assistant. I can help you with:")
        print("  • Property prices and costs")
        print("  • Plot sizes (5 Marla, 10 Marla, 1 Kanal)")
        print("  • DHA phases information (Phase 1 to 10)")
        print("  • Commercial and residential properties")
        print("  • Investment advice")
        print("\nType 'quit', 'exit', or 'bye' to end the chat")
        print("Type 'help' for assistance")
        print("-"*70)

        chat_history = []

        while True:
            try:
                # Get user input
                user_input = input("\n👤 You: ").strip()

                # Handle empty input
                if not user_input:
                    continue

                # Check for exit commands
                exit_commands = ['quit', 'exit', 'bye', 'goodbye', 'stop', 'end']
                if user_input.lower() in exit_commands:
                    print(f"\n🤖 Goodbye! Thank you for using our DHA property service. 🏡")
                    break

                # Check for help
                if user_input.lower() == 'help':
                    print("\n🤖 I can help you with:")
                    print("  1. Property prices: 'Price of 5 Marla plot'")
                    print("  2. Phase information: 'Tell me about Phase 8'")
                    print("  3. Availability: 'Is Phase 6 available?'")
                    print("  4. Comparisons: 'Phase 6 vs Phase 8'")
                    print("  5. Investment: 'Best phase for investment'")
                    print("\nJust ask your question naturally!")
                    continue

                # Generate response
                print("🤖 Assistant: ", end="", flush=True)
                response = self.generate_response(user_input)
                print(response)

                # Store in history
                chat_history.append({
                    "user": user_input,
                    "bot": response[:50] + "..." if len(response) > 50 else response
                })

                # Show hint after 5 messages
                if len(chat_history) == 5:
                    print("\n💡 Tip: You can ask about specific phases or plot sizes!")

            except KeyboardInterrupt:
                print("\n\n🤖 Chat interrupted. Goodbye!")
                break
            except Exception as e:
                print(f"\n⚠️  Error: {e}")
                print("🤖 I encountered an issue. Please try asking differently.")

# ========== RUN THE CHATBOT ==========
print("\n🚀 Initializing Hybrid DHA Chatbot...")
print("-" * 50)

# Create chatbot instance
chatbot = HybridDHAChatbot()

# Quick test
print("\nRunning quick test to ensure everything works...")
chatbot.quick_test()

# Ask user if they want to chat
print("\n" + "="*70)
print("💬 READY FOR INTERACTIVE CHAT")
print("="*70)

start_chat = input("\nStart interactive chat? (yes/no): ").strip().lower()

if start_chat in ['yes', 'y', 'yeah', 'yep', 'ok', 'okay']:
    chatbot.interactive_chat()
else:
    print("\n✅ Chatbot is ready! You can start chat anytime by running:")
    print("   chatbot.interactive_chat()")
    print("\nOr test with:")
    print("   chatbot.generate_response('Your question here')")

print("\n" + "="*70)
print("🏡 DHA PROPERTY CHATBOT - READY TO USE")
print("="*70)