# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZSrtpq5J1JdcwETTU8vBQ1iyncJnA6u
"""

!pip install pandas numpy scikit-learn tensorflow matplotlib seaborn requests django djangorestframework

import pandas as pd
import numpy as np
import json
import requests
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import LSTM, Dense, Dropout, Embedding, Input, RepeatVector, TimeDistributed
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import warnings
import pickle
warnings.filterwarnings('ignore')

print("STEP 1: CREATING SAMPLE DATA")
print("\n" + "="*60)
print("="*60)

# Create 100 users data directly in Colab
users_data = [
  {
    "email": "john.smith@techcorp.com",
    "first_name": "John",
    "last_name": "Smith",
    "age": 32,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Software Engineer"
  },
  {
    "email": "sarah.johnson@medcenter.org",
    "first_name": "Sarah",
    "last_name": "Johnson",
    "age": 28,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Doctor"
  },
  {
    "email": "robert.williams@university.edu",
    "first_name": "Robert",
    "last_name": "Williams",
    "age": 45,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Professor"
  },
  {
    "email": "emily.davis@designstudio.com",
    "first_name": "Emily",
    "last_name": "Davis",
    "age": 29,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 78000.0,
    "occupation": "UX Designer"
  },
  {
    "email": "michael.brown@finance.com",
    "first_name": "Michael",
    "last_name": "Brown",
    "age": 35,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 110000.0,
    "occupation": "Financial Analyst"
  },
  {
    "email": "jennifer.wilson@techstartup.com",
    "first_name": "Jennifer",
    "last_name": "Wilson",
    "age": 26,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 92000.0,
    "occupation": "Data Scientist"
  },
  {
    "email": "david.miller@construct.com",
    "first_name": "David",
    "last_name": "Miller",
    "age": 41,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 88000.0,
    "occupation": "Construction Manager"
  },
  {
    "email": "lisa.moore@hospital.org",
    "first_name": "Lisa",
    "last_name": "Moore",
    "age": 33,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Nurse Practitioner"
  },
  {
    "email": "william.taylor@laws.com",
    "first_name": "William",
    "last_name": "Taylor",
    "age": 38,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Lawyer"
  },
  {
    "email": "amanda.anderson@school.edu",
    "first_name": "Amanda",
    "last_name": "Anderson",
    "age": 42,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 65000.0,
    "occupation": "Teacher"
  },
  {
    "email": "james.thomas@automotive.com",
    "first_name": "James",
    "last_name": "Thomas",
    "age": 31,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 72000.0,
    "occupation": "Mechanical Engineer"
  },
  {
    "email": "michelle.jackson@retail.com",
    "first_name": "Michelle",
    "last_name": "Jackson",
    "age": 27,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 58000.0,
    "occupation": "Marketing Manager"
  },
  {
    "email": "charles.white@consulting.com",
    "first_name": "Charles",
    "last_name": "White",
    "age": 36,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 132000.0,
    "occupation": "Management Consultant"
  },
  {
    "email": "sophia.harris@agency.com",
    "first_name": "Sophia",
    "last_name": "Harris",
    "age": 30,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 76000.0,
    "occupation": "Account Executive"
  },
  {
    "email": "daniel.martin@pharma.com",
    "first_name": "Daniel",
    "last_name": "Martin",
    "age": 34,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 98000.0,
    "occupation": "Research Scientist"
  },
  {
    "email": "olivia.thompson@nonprofit.org",
    "first_name": "Olivia",
    "last_name": "Thompson",
    "age": 25,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 52000.0,
    "occupation": "Social Worker"
  },
  {
    "email": "matthew.garcia@techgiant.com",
    "first_name": "Matthew",
    "last_name": "Garcia",
    "age": 29,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 115000.0,
    "occupation": "DevOps Engineer"
  },
  {
    "email": "elizabeth.rodriguez@hospital.org",
    "first_name": "Elizabeth",
    "last_name": "Rodriguez",
    "age": 37,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 89000.0,
    "occupation": "Pharmacist"
  },
  {
    "email": "christopher.lewis@airline.com",
    "first_name": "Christopher",
    "last_name": "Lewis",
    "age": 40,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 102000.0,
    "occupation": "Pilot"
  },
  {
    "email": "ashley.walker@fashion.com",
    "first_name": "Ashley",
    "last_name": "Walker",
    "age": 24,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 48000.0,
    "occupation": "Fashion Designer"
  },
  {
    "email": "ethan.wilson@finance.net",
    "first_name": "Ethan",
    "last_name": "Wilson",
    "age": 28,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 82000.0,
    "occupation": "Investment Banker"
  },
  {
    "email": "chloe.clark@healthcare.org",
    "first_name": "Chloe",
    "last_name": "Clark",
    "age": 31,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Physician Assistant"
  },
  {
    "email": "benjamin.robinson@research.edu",
    "first_name": "Benjamin",
    "last_name": "Robinson",
    "age": 44,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Research Director"
  },
  {
    "email": "mia.lee@techstartup.io",
    "first_name": "Mia",
    "last_name": "Lee",
    "age": 27,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Product Manager"
  },
  {
    "email": "alexander.king@consulting.group",
    "first_name": "Alexander",
    "last_name": "King",
    "age": 36,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 135000.0,
    "occupation": "Senior Consultant"
  },
  {
    "email": "ava.scott@datascience.ai",
    "first_name": "Ava",
    "last_name": "Scott",
    "age": 25,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 88000.0,
    "occupation": "Machine Learning Engineer"
  },
  {
    "email": "samuel.wright@engineering.com",
    "first_name": "Samuel",
    "last_name": "Wright",
    "age": 39,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 112000.0,
    "occupation": "Civil Engineer"
  },
  {
    "email": "grace.young@medical.org",
    "first_name": "Grace",
    "last_name": "Young",
    "age": 34,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 115000.0,
    "occupation": "Anesthesiologist"
  },
  {
    "email": "joseph.hall@legalpartners.com",
    "first_name": "Joseph",
    "last_name": "Hall",
    "age": 41,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 160000.0,
    "occupation": "Partner Lawyer"
  },
  {
    "email": "ella.allen@education.gov",
    "first_name": "Ella",
    "last_name": "Allen",
    "age": 46,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 72000.0,
    "occupation": "School Principal"
  },
  {
    "email": "henry.green@autoindustry.com",
    "first_name": "Henry",
    "last_name": "Green",
    "age": 33,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Automotive Engineer"
  },
  {
    "email": "lily.baker@advertising.com",
    "first_name": "Lily",
    "last_name": "Baker",
    "age": 29,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 67000.0,
    "occupation": "Creative Director"
  },
  {
    "email": "jackson.adams@strategy.com",
    "first_name": "Jackson",
    "last_name": "Adams",
    "age": 37,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 142000.0,
    "occupation": "Strategy Consultant"
  },
  {
    "email": "scarlett.nelson@realestate.com",
    "first_name": "Scarlett",
    "last_name": "Nelson",
    "age": 32,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 92000.0,
    "occupation": "Real Estate Broker"
  },
  {
    "email": "lucas.carter@biotech.com",
    "first_name": "Lucas",
    "last_name": "Carter",
    "age": 35,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 110000.0,
    "occupation": "Biotech Researcher"
  },
  {
    "email": "zoey.mitchell@community.org",
    "first_name": "Zoey",
    "last_name": "Mitchell",
    "age": 26,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 58000.0,
    "occupation": "Community Organizer"
  },
  {
    "email": "logan.perez@cloudtech.com",
    "first_name": "Logan",
    "last_name": "Perez",
    "age": 30,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 128000.0,
    "occupation": "Cloud Architect"
  },
  {
    "email": "hannah.roberts@pharmacy.org",
    "first_name": "Hannah",
    "last_name": "Roberts",
    "age": 38,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 96000.0,
    "occupation": "Clinical Pharmacist"
  },
  {
    "email": "ryan.turner@aviation.com",
    "first_name": "Ryan",
    "last_name": "Turner",
    "age": 42,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 118000.0,
    "occupation": "Commercial Pilot"
  },
  {
    "email": "victoria.phillips@design.co",
    "first_name": "Victoria",
    "last_name": "Phillips",
    "age": 25,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 55000.0,
    "occupation": "Interior Designer"
  },
  {
    "email": "carter.campbell@fintech.io",
    "first_name": "Carter",
    "last_name": "Campbell",
    "age": 29,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 95000.0,
    "occupation": "FinTech Analyst"
  },
  {
    "email": "zoe.parker@hospital.net",
    "first_name": "Zoe",
    "last_name": "Parker",
    "age": 32,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 108000.0,
    "occupation": "Emergency Doctor"
  },
  {
    "email": "gabriel.edwards@harvard.edu",
    "first_name": "Gabriel",
    "last_name": "Edwards",
    "age": 48,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 140000.0,
    "occupation": "Department Head"
  },
  {
    "email": "penelope.collins@uiux.design",
    "first_name": "Penelope",
    "last_name": "Collins",
    "age": 28,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 82000.0,
    "occupation": "UI Designer"
  },
  {
    "email": "jayden.stewart@wealth.com",
    "first_name": "Jayden",
    "last_name": "Stewart",
    "age": 37,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 155000.0,
    "occupation": "Wealth Manager"
  },
  {
    "email": "nora.morris@analytics.co",
    "first_name": "Nora",
    "last_name": "Morris",
    "age": 24,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 78000.0,
    "occupation": "Business Analyst"
  },
  {
    "email": "leo.rogers@builders.com",
    "first_name": "Leo",
    "last_name": "Rogers",
    "age": 43,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 98000.0,
    "occupation": "Project Manager"
  },
  {
    "email": "riley.reed@healthsystem.org",
    "first_name": "Riley",
    "last_name": "Reed",
    "age": 35,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Cardiologist"
  },
  {
    "email": "aiden.cook@lawfirm.com",
    "first_name": "Aiden",
    "last_name": "Cook",
    "age": 39,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 175000.0,
    "occupation": "Corporate Lawyer"
  },
  {
    "email": "layla.morgan@university.edu",
    "first_name": "Layla",
    "last_name": "Morgan",
    "age": 47,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 68000.0,
    "occupation": "Assistant Professor"
  },
  {
    "email": "mateo.bell@electric.com",
    "first_name": "Mateo",
    "last_name": "Bell",
    "age": 34,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 90000.0,
    "occupation": "Electrical Engineer"
  },
  {
    "email": "aurora.cooper@branding.com",
    "first_name": "Aurora",
    "last_name": "Cooper",
    "age": 30,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 72000.0,
    "occupation": "Brand Manager"
  },
  {
    "email": "dylan.richardson@mckinsey.com",
    "first_name": "Dylan",
    "last_name": "Richardson",
    "age": 38,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 165000.0,
    "occupation": "Partner Consultant"
  },
  {
    "email": "clara.wood@salesforce.com",
    "first_name": "Clara",
    "last_name": "Wood",
    "age": 33,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 88000.0,
    "occupation": "Sales Director"
  },
  {
    "email": "axel.price@genetics.com",
    "first_name": "Axel",
    "last_name": "Price",
    "age": 36,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Geneticist"
  },
  {
    "email": "stella.bennett@youth.org",
    "first_name": "Stella",
    "last_name": "Bennett",
    "age": 27,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 54000.0,
    "occupation": "Youth Counselor"
  },
  {
    "email": "jaxon.hughes@google.com",
    "first_name": "Jaxon",
    "last_name": "Hughes",
    "age": 31,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 135000.0,
    "occupation": "Site Reliability Engineer"
  },
  {
    "email": "luna.flores@medicalcenter.org",
    "first_name": "Luna",
    "last_name": "Flores",
    "age": 39,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 102000.0,
    "occupation": "Radiologist"
  },
  {
    "email": "ezra.washington@delta.com",
    "first_name": "Ezra",
    "last_name": "Washington",
    "age": 44,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Airline Captain"
  },
  {
    "email": "maya.butler@luxury.com",
    "first_name": "Maya",
    "last_name": "Butler",
    "age": 26,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 62000.0,
    "occupation": "Luxury Retail Manager"
  },
  {
    "email": "liam.foster@banking.com",
    "first_name": "Liam",
    "last_name": "Foster",
    "age": 30,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 92000.0,
    "occupation": "Risk Analyst"
  },
  {
    "email": "ellie.gonzalez@childrens.org",
    "first_name": "Ellie",
    "last_name": "Gonzalez",
    "age": 33,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 115000.0,
    "occupation": "Pediatrician"
  },
  {
    "email": "owen.bryant@mit.edu",
    "first_name": "Owen",
    "last_name": "Bryant",
    "age": 49,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Research Professor"
  },
  {
    "email": "aria.russell@apple.com",
    "first_name": "Aria",
    "last_name": "Russell",
    "age": 29,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 115000.0,
    "occupation": "iOS Developer"
  },
  {
    "email": "levi.griffin@hedgefund.com",
    "first_name": "Levi",
    "last_name": "Griffin",
    "age": 36,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 185000.0,
    "occupation": "Hedge Fund Manager"
  },
  {
    "email": "elena.diaz@dataviz.com",
    "first_name": "Elena",
    "last_name": "Diaz",
    "age": 25,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Data Visualization Specialist"
  },
  {
    "email": "silas.hayes@infrastructure.com",
    "first_name": "Silas",
    "last_name": "Hayes",
    "age": 40,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Infrastructure Engineer"
  },
  {
    "email": "nadia.porter@clinic.org",
    "first_name": "Nadia",
    "last_name": "Porter",
    "age": 36,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 135000.0,
    "occupation": "Surgeon"
  },
  {
    "email": "caleb.simmons@justice.gov",
    "first_name": "Caleb",
    "last_name": "Simmons",
    "age": 42,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 155000.0,
    "occupation": "Federal Prosecutor"
  },
  {
    "email": "rose.fisher@college.edu",
    "first_name": "Rose",
    "last_name": "Fisher",
    "age": 44,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 75000.0,
    "occupation": "College Professor"
  },
  {
    "email": "jonah.holland@ford.com",
    "first_name": "Jonah",
    "last_name": "Holland",
    "age": 32,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Automotive Designer"
  },
  {
    "email": "iris.gibson@coca-cola.com",
    "first_name": "Iris",
    "last_name": "Gibson",
    "age": 31,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 78000.0,
    "occupation": "Product Marketing Manager"
  },
  {
    "email": "theodore.weber@bain.com",
    "first_name": "Theodore",
    "last_name": "Weber",
    "age": 39,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 172000.0,
    "occupation": "Principal Consultant"
  },
  {
    "email": "lilith.mcdonald@tourism.com",
    "first_name": "Lilith",
    "last_name": "McDonald",
    "age": 34,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 82000.0,
    "occupation": "Tourism Director"
  },
  {
    "email": "asher.lane@vaccine.com",
    "first_name": "Asher",
    "last_name": "Lane",
    "age": 37,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 118000.0,
    "occupation": "Vaccine Researcher"
  },
  {
    "email": "ada.fletcher@environment.org",
    "first_name": "Ada",
    "last_name": "Fletcher",
    "age": 28,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 56000.0,
    "occupation": "Environmental Scientist"
  },
  {
    "email": "maxwell.schwartz@netflix.com",
    "first_name": "Maxwell",
    "last_name": "Schwartz",
    "age": 32,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Streaming Engineer"
  },
  {
    "email": "ruby.wagner@mayo.edu",
    "first_name": "Ruby",
    "last_name": "Wagner",
    "age": 41,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 110000.0,
    "occupation": "Oncologist"
  },
  {
    "email": "kai.snyder@united.com",
    "first_name": "Kai",
    "last_name": "Snyder",
    "age": 45,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 132000.0,
    "occupation": "Flight Instructor"
  },
  {
    "email": "freya.lambert@casino.com",
    "first_name": "Freya",
    "last_name": "Lambert",
    "age": 27,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 68000.0,
    "occupation": "Casino Manager"
  },
  {
    "email": "elias.mason@citi.com",
    "first_name": "Elias",
    "last_name": "Mason",
    "age": 29,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 102000.0,
    "occupation": "Investment Analyst"
  },
  {
    "email": "juliet.beck@kaiser.org",
    "first_name": "Juliet",
    "last_name": "Beck",
    "age": 34,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Psychiatrist"
  },
  {
    "email": "arthur.newman@tufts.edu",
    "first_name": "Arthur",
    "last_name": "Newman",
    "age": 50,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 150000.0,
    "occupation": "Dean of Faculty"
  },
  {
    "email": "eden.lucas@adobe.com",
    "first_name": "Eden",
    "last_name": "Lucas",
    "age": 30,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 98000.0,
    "occupation": "Graphic Designer"
  },
  {
    "email": "roman.owens@trading.com",
    "first_name": "Roman",
    "last_name": "Owens",
    "age": 35,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 195000.0,
    "occupation": "Quantitative Trader"
  },
  {
    "email": "alexis.patrick@ibm.com",
    "first_name": "Alexis",
    "last_name": "Patrick",
    "age": 26,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 92000.0,
    "occupation": "AI Engineer"
  },
  {
    "email": "tobias.payne@oilgas.com",
    "first_name": "Tobias",
    "last_name": "Payne",
    "age": 42,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 122000.0,
    "occupation": "Petroleum Engineer"
  },
  {
    "email": "camille.boone@mercy.org",
    "first_name": "Camille",
    "last_name": "Boone",
    "age": 37,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Neurologist"
  },
  {
    "email": "spencer.barry@supremecourt.gov",
    "first_name": "Spencer",
    "last_name": "Barry",
    "age": 47,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 190000.0,
    "occupation": "Constitutional Lawyer"
  },
  {
    "email": "lydia.ball@k12.edu",
    "first_name": "Lydia",
    "last_name": "Ball",
    "age": 39,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 82000.0,
    "occupation": "Special Education Teacher"
  },
  {
    "email": "brody.logan@tesla.com",
    "first_name": "Brody",
    "last_name": "Logan",
    "age": 33,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 115000.0,
    "occupation": "EV Engineer"
  },
  {
    "email": "savannah.owens@nike.com",
    "first_name": "Savannah",
    "last_name": "Owens",
    "age": 32,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Sports Marketing Manager"
  },
  {
    "email": "jude.curtis@ey.com",
    "first_name": "Jude",
    "last_name": "Curtis",
    "age": 40,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 168000.0,
    "occupation": "Audit Partner"
  },
  {
    "email": "delilah.harvey@marriott.com",
    "first_name": "Delilah",
    "last_name": "Harvey",
    "age": 35,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Hotel General Manager"
  },
  {
    "email": "bennett.wade@pfizer.com",
    "first_name": "Bennett",
    "last_name": "Wade",
    "age": 38,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 128000.0,
    "occupation": "Clinical Trial Manager"
  },
  {
    "email": "remi.day@wildlife.org",
    "first_name": "Remi",
    "last_name": "Day",
    "age": 29,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 59000.0,
    "occupation": "Wildlife Biologist"
  },
  {
    "email": "finn.cobb@nvidia.com",
    "first_name": "Finn",
    "last_name": "Cobb",
    "age": 31,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 155000.0,
    "occupation": "GPU Architect"
  },
  {
    "email": "cora.brewer@clevelandclinic.org",
    "first_name": "Cora",
    "last_name": "Brewer",
    "age": 43,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 118000.0,
    "occupation": "Cardiac Surgeon"
  },
  {
    "email": "kellen.leonard@southwest.com",
    "first_name": "Kellen",
    "last_name": "Leonard",
    "age": 46,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 138000.0,
    "occupation": "Chief Pilot"
  },
  {
    "email": "jolie.todd@eventplanning.com",
    "first_name": "Jolie",
    "last_name": "Todd",
    "age": 28,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 71000.0,
    "occupation": "Event Planner"
  },
  {
    "email": "dash.blair@morganstanley.com",
    "first_name": "Dash",
    "last_name": "Blair",
    "age": 30,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 112000.0,
    "occupation": "Portfolio Manager"
  }
]


print(f"✅ Loaded {len(users_data)} users for chatbot training")

def prepare_chatbot_data(users_data):
    """Create conversation training pairs with VARIABLE responses for the 100 users"""
    training_pairs = []

    # Template responses with placeholders
    response_templates = [
        "{name} is {age} years old and works as a {occupation} in {city}, {country}.",
        "{name} {last_name} is a {age}-year-old {occupation} based in {city}.",
        "{name}'s occupation is {occupation} and lives in {city}.",
        "{name} is {age} years old, earning ${income:,} per year as a {occupation}.",
        "{name} lives in {city}, {country}. {name} is a {occupation}.",
        "Hello {name}! I see you're a {age}-year-old {occupation} from {city}.",
        "Based on your profile, {name}: Age {age}, {occupation} in {city}.",
        "{name}, your annual income is ${income:,} as a {occupation} in {city}.",
        "{name} {last_name} lives in {city}, {country}, and works as a {occupation}.",
        "Here is {name}'s profile: {age} years old, {occupation}, located in {city}.",
    ]

    for user in users_data:
        # User queries
        queries = [
            f"Tell me about myself",
            f"What's my profile?",
            f"Who am I?",
            f"Describe my profile",
            f"What do you know about me?",
            f"Tell me about {user['first_name']}",
            f"What is {user['first_name']}'s occupation?",
            f"Where does {user['first_name']} live?",
            f"How old is {user['first_name']}?",
            f"What does {user['first_name']} do?",
            f"What is my income?",
            f"How much do I earn?",
            f"What city do I live in?",
            f"What country am I from?",
            f"Give me my full profile",
            f"What is {user['first_name']}'s full name?",
            f"What is {user['first_name']}'s email?",
            f"How much does {user['first_name']} earn?",
            f"Where is {user['first_name']} based?",
        ]

        # Generate multiple response variations for each query
        for query in queries:
            # Use 3 different templates for each query
            for i in range(3):
                template = response_templates[i % len(response_templates)]
                response = template.format(
                    name=user['first_name'],
                    last_name=user['last_name'],
                    age=user['age'],
                    occupation=user['occupation'].lower(),
                    city=user['city'],
                    country=user['country'],
                    income=user['income']
                )
                training_pairs.append((query.lower(), response))

    # Add general conversations
    general_pairs = [
        ("hello", "Hello! How can I help you today?"),
        ("hi", "Hi there! What can I do for you?"),
        ("how are you?", "I'm doing great! How about you?"),
        ("what can you do?", "I can tell you about user profiles and answer questions about them."),
        ("thank you", "You're welcome!"),
        ("bye", "Goodbye! Have a great day!"),
        ("who created you?", "I was created as an AI chatbot."),
        ("help", "I can help with user profiles. Try asking about someone's occupation or location."),
        ("list all users", f"I have data on {len(users_data)} users with various occupations."),
        ("who are you?", "I'm an AI chatbot trained to provide user information."),
    ]

    training_pairs.extend(general_pairs)

    return training_pairs

# Create training data
training_pairs = prepare_chatbot_data(users_data)
print(f"✅ Created {len(training_pairs)} training conversation pairs")

print("\n📋 Sample training pairs:")
for i in range(3):
    print(f"  User: '{training_pairs[i][0]}'")
    print(f"  Bot:  '{training_pairs[i][1]}'")
    print()

print("\n" + "="*60)
print("BUILDING IMPROVED MODEL")
print("="*60)

inputs = [pair[0] for pair in training_pairs]
outputs = [pair[1] for pair in training_pairs]

input_tokenizer = Tokenizer(num_words=2000, oov_token="<OOV>")
input_tokenizer.fit_on_texts(inputs)
input_sequences = input_tokenizer.texts_to_sequences(inputs)
max_input_len = 15
input_padded = pad_sequences(input_sequences, maxlen=max_input_len, padding='post')

output_tokenizer = Tokenizer(num_words=2000, oov_token="<OOV>")
output_tokenizer.fit_on_texts(outputs)
output_sequences = output_tokenizer.texts_to_sequences(outputs)
max_output_len = 30
output_padded = pad_sequences(output_sequences, maxlen=max_output_len, padding='post')

print(f"📊 Data shapes:")
print(f"   Input shape: {input_padded.shape}")
print(f"   Output shape: {output_padded.shape}")
print(f"   Input vocab size: {len(input_tokenizer.word_index)}")
print(f"   Output vocab size: {len(output_tokenizer.word_index)}")

vocab_size = len(output_tokenizer.word_index) + 1

encoder_inputs = Input(shape=(max_input_len,))
encoder_embedding = Embedding(len(input_tokenizer.word_index) + 1, 128)(encoder_inputs)
encoder_lstm = LSTM(128, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_embedding)
encoder_states = [state_h, state_c]

decoder_inputs = Input(shape=(max_output_len,))
decoder_embedding = Embedding(vocab_size, 128)(decoder_inputs)
decoder_lstm = LSTM(128, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)
decoder_dense = Dense(vocab_size, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

print("\n" + "="*60)
print("TRAINING MODEL")
print("="*60)

decoder_input_data = np.zeros_like(output_padded)
decoder_input_data[:, 1:] = output_padded[:, :-1]
decoder_input_data[:, 0] = output_tokenizer.word_index['<OOV>']

decoder_target_data = np.expand_dims(output_padded, -1)

history = model.fit(
    [input_padded, decoder_input_data],
    decoder_target_data,
    epochs=15,
    batch_size=16,
    validation_split=0.2,
    verbose=1
)

print("\n" + "="*60)
print("BUILDING INFERENCE MODEL")
print("="*60)

encoder_model = Model(encoder_inputs, encoder_states)

# NEW decoder_state_input_h = Input(shape=(256,), name="dec_h")   # FIX SIZE!
decoder_state_input_c = Input(shape=(256,), name="dec_c")
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

# New decoder_input_single = Input(shape=(1,), name="dec_input")

# NEW decoder_input_embed = decoder_embedding_layer(decoder_input_single)

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_input_embed, initial_state=decoder_states_inputs)

decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(
    [decoder_input_single] + decoder_states_inputs,
    [decoder_outputs] + decoder_states
)

# new # start_token = output_tokenizer.word_index['<start>']
stop_token = output_tokenizer.word_index['<end>']

def decode_sequence(input_seq):
    states_value = encoder_model.predict(input_seq, verbose=0)

    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = start_token

    decoded_sentence = ""

    while True:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value, verbose=0)

        sampled_token_index = np.argmax(output_tokens[0, -1, :])

        if sampled_token_index == stop_token:
            break

        sampled_word = output_tokenizer.index_word.get(sampled_token_index, "")

        decoded_sentence += " " + sampled_word

        target_seq[0, 0] = sampled_token_index
        states_value = [h, c]

        if len(decoded_sentence.split()) > max_output_len:
            break

    return decoded_sentence.strip()













decoder_state_input_h = Input(shape=(128,))
decoder_state_input_c = Input(shape=(128,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_embedding, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

print("\n" + "="*60)
print("TESTING THE CHATBOT")
print("="*60)

def decode_sequence(input_seq):
    """Decode sequence for inference"""
    # Encode the input as state vectors
    states_value = encoder_model.predict(input_seq, verbose=0)

    # Generate empty target sequence of length 1
    target_seq = np.zeros((1, 1))
    # Populate the first character with start token
    target_seq[0, 0] = output_tokenizer.word_index['<OOV>']

    # Sampling loop
    stop_condition = False
    decoded_sentence = ''
    max_decoded_len = 30

    while not stop_condition and len(decoded_sentence.split()) < max_decoded_len:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value, verbose=0)

        # Sample a token
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_word = None

        for word, index in output_tokenizer.word_index.items():
            if index == sampled_token_index:
                sampled_word = word
                break

        if sampled_word is None or sampled_word == '<OOV>':
            sampled_word = ''

        # Exit condition: either max length or stop word
        if (sampled_word == '' or
            len(decoded_sentence.split()) >= max_decoded_len - 1):
            stop_condition = True
        else:
            decoded_sentence += ' ' + sampled_word

        # Update the target sequence
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = sampled_token_index

        # Update states
        states_value = [h, c]

    return decoded_sentence.strip()

def predict_response(user_input, user_context=None):
    """Generate response using trained model"""
    # Preprocess input
    input_seq = input_tokenizer.texts_to_sequences([user_input.lower()])
    input_padded_seq = pad_sequences(input_seq, maxlen=max_input_len, padding='post')

    # Generate response
    response = decode_sequence(input_padded_seq)

    # Personalize if user context provided
    if user_context and user_context.get('first_name'):
        name = user_context['first_name']
        # Simple personalization
        if 'you' in response.lower():
            response = response.replace('you', name)
            response = response.replace('your', f"{name}'s")

    return response if response else "I'm not sure how to answer that."

    # Test with different inputs
test_inputs = [
    "hello",
    "tell me about john",
    "what does sarah do",
    "where does michael live",
    "how old is emily",
    "what is my income",
    "bye"
]

print("🤖 Chatbot Testing:")
print("-" * 50)

for test_input in test_inputs:
    response = predict_response(test_input)
    print(f"👤 User: {test_input}")
    print(f"🤖 Bot: {response}")
    print()

print("\n" + "="*60)
print("SAVING MODEL")
print("="*60)

# Save all components
model.save('chatbot_seq2seq_model.h5')
encoder_model.save('chatbot_encoder_model.h5')
decoder_model.save('chatbot_decoder_model.h5')

with open('input_tokenizer.pkl', 'wb') as f:
    pickle.dump(input_tokenizer, f)

with open('output_tokenizer.pkl', 'wb') as f:
    pickle.dump(output_tokenizer, f)

with open('config.pkl', 'wb') as f:
    config = {
        'max_input_len': max_input_len,
        'max_output_len': max_output_len
    }
    pickle.dump(config, f)

print("✅ Models and tokenizers saved successfully!")

print("\n" + "="*60)
print("DJANGO INTEGRATION GUIDELINES")
print("="*60)

print("""
For Django integration:

1. Place these files in your Django project:
   - chatbot_seq2seq_model.h5
   - chatbot_encoder_model.h5
   - chatbot_decoder_model.h5
   - input_tokenizer.pkl
   - output_tokenizer.pkl
   - config.pkl

2. Create a Django view like this:

import pickle
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences

class ChatbotView(View):
    def __init__(self):
        # Load models once
        self.encoder_model = load_model('chatbot_encoder_model.h5')
        self.decoder_model = load_model('chatbot_decoder_model.h5')

        with open('input_tokenizer.pkl', 'rb') as f:
            self.input_tokenizer = pickle.load(f)

        with open('output_tokenizer.pkl', 'rb') as f:
            self.output_tokenizer = pickle.load(f)

        with open('config.pkl', 'rb') as f:
            self.config = pickle.load(f)

    def post(self, request):
        user_input = request.POST.get('message', '')
        user_id = request.user.id  # Get current user

        # Get user context from database
        user_context = User.objects.get(id=user_id)

        # Generate response
        response = self.generate_response(user_input, user_context)

        return JsonResponse({'response': response})
""")

# In your Colab notebook, after training:

print("\n" + "="*60)
print("CREATING INFERENCE MODELS")
print("="*60)

# Build inference models
# Encoder inference model
encoder_inputs = model.input[0]  # input_1
encoder_outputs, state_h_enc, state_c_enc = model.layers[4].output  # lstm_1
encoder_states = [state_h_enc, state_c_enc]
encoder_model = Model(encoder_inputs, encoder_states)

# Decoder inference model
decoder_inputs = model.input[1]  # input_2
decoder_state_input_h = Input(shape=(128,))
decoder_state_input_c = Input(shape=(128,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_lstm = model.layers[5]
decoder_embedding = model.layers[3]
decoder_dense = model.layers[7]

decoder_outputs, state_h_dec, state_c_dec = decoder_lstm(
    decoder_embedding(decoder_inputs), initial_state=decoder_states_inputs)
decoder_states = [state_h_dec, state_c_dec]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

print("✅ Inference models created")

print("\n" + "="*60)
print("SAVING ALL FILES FOR DJANGO")
print("="*60)

# Save ALL required files
import pickle

# 1. Save encoder model
encoder_model.save('chatbot_encoder.h5')
print("✅ Saved: chatbot_encoder.h5")

# 2. Save decoder model
decoder_model.save('chatbot_decoder.h5')
print("✅ Saved: chatbot_decoder.h5")

# 3. Save input tokenizer
with open('input_tokenizer.pkl', 'wb') as f:
    pickle.dump(input_tokenizer, f)
print("✅ Saved: input_tokenizer.pkl")

# 4. Save output tokenizer
with open('output_tokenizer.pkl', 'wb') as f:
    pickle.dump(output_tokenizer, f)
print("✅ Saved: output_tokenizer.pkl")

# 5. Save config
config = {
    'max_input_len': max_input_len,
    'max_output_len': max_output_len
}
with open('config.pkl', 'wb') as f:
    pickle.dump(config, f)
print("✅ Saved: config.pkl")

# 6. Save sample users data (optional, for reference)
with open('sample_users.pkl', 'wb') as f:
    pickle.dump(users_data, f)
print("✅ Saved: sample_users.pkl")

print("\n" + "="*60)
print("DOWNLOADING FILES")
print("="*60)

from google.colab import files

files_to_download = [
    'chatbot_encoder.h5',
    'chatbot_decoder.h5',
    'input_tokenizer.pkl',
    'output_tokenizer.pkl',
    'config.pkl',
    'sample_users.pkl'
]

for file in files_to_download:
    try:
        files.download(file)
        print(f"📥 Downloaded: {file}")
    except:
        print(f"⚠️  Could not download: {file}")





