# -*- coding: utf-8 -*-
"""Try.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106JQp0zWSuVC7mQ3MipQCRGTzrf0bepQ
"""

!pip install pandas numpy scikit-learn tensorflow matplotlib seaborn requests django djangorestframework

import random
import pandas as pd
import numpy as np
import json
import requests
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import LSTM, Dense, Dropout, Embedding, Input, RepeatVector, TimeDistributed
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import warnings
import pickle
warnings.filterwarnings('ignore')

print("STEP 1: CREATING SAMPLE DATA")
print("\n" + "="*60)
print("="*60)

# Create 100 users data directly in Colab
users_data = [
  {
    "email": "john.smith@techcorp.com",
    "first_name": "John",
    "last_name": "Smith",
    "age": 32,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Software Engineer"
  },
  {
    "email": "sarah.johnson@medcenter.org",
    "first_name": "Sarah",
    "last_name": "Johnson",
    "age": 28,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Doctor"
  },
  {
    "email": "robert.williams@university.edu",
    "first_name": "Robert",
    "last_name": "Williams",
    "age": 45,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Professor"
  },
  {
    "email": "emily.davis@designstudio.com",
    "first_name": "Emily",
    "last_name": "Davis",
    "age": 29,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 78000.0,
    "occupation": "UX Designer"
  },
  {
    "email": "michael.brown@finance.com",
    "first_name": "Michael",
    "last_name": "Brown",
    "age": 35,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 110000.0,
    "occupation": "Financial Analyst"
  },
  {
    "email": "jennifer.wilson@techstartup.com",
    "first_name": "Jennifer",
    "last_name": "Wilson",
    "age": 26,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 92000.0,
    "occupation": "Data Scientist"
  },
  {
    "email": "david.miller@construct.com",
    "first_name": "David",
    "last_name": "Miller",
    "age": 41,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 88000.0,
    "occupation": "Construction Manager"
  },
  {
    "email": "lisa.moore@hospital.org",
    "first_name": "Lisa",
    "last_name": "Moore",
    "age": 33,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Nurse Practitioner"
  },
  {
    "email": "william.taylor@laws.com",
    "first_name": "William",
    "last_name": "Taylor",
    "age": 38,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Lawyer"
  },
  {
    "email": "amanda.anderson@school.edu",
    "first_name": "Amanda",
    "last_name": "Anderson",
    "age": 42,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 65000.0,
    "occupation": "Teacher"
  },
  {
    "email": "james.thomas@automotive.com",
    "first_name": "James",
    "last_name": "Thomas",
    "age": 31,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 72000.0,
    "occupation": "Mechanical Engineer"
  },
  {
    "email": "michelle.jackson@retail.com",
    "first_name": "Michelle",
    "last_name": "Jackson",
    "age": 27,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 58000.0,
    "occupation": "Marketing Manager"
  },
  {
    "email": "charles.white@consulting.com",
    "first_name": "Charles",
    "last_name": "White",
    "age": 36,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 132000.0,
    "occupation": "Management Consultant"
  },
  {
    "email": "sophia.harris@agency.com",
    "first_name": "Sophia",
    "last_name": "Harris",
    "age": 30,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 76000.0,
    "occupation": "Account Executive"
  },
  {
    "email": "daniel.martin@pharma.com",
    "first_name": "Daniel",
    "last_name": "Martin",
    "age": 34,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 98000.0,
    "occupation": "Research Scientist"
  },
  {
    "email": "olivia.thompson@nonprofit.org",
    "first_name": "Olivia",
    "last_name": "Thompson",
    "age": 25,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 52000.0,
    "occupation": "Social Worker"
  },
  {
    "email": "matthew.garcia@techgiant.com",
    "first_name": "Matthew",
    "last_name": "Garcia",
    "age": 29,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 115000.0,
    "occupation": "DevOps Engineer"
  },
  {
    "email": "elizabeth.rodriguez@hospital.org",
    "first_name": "Elizabeth",
    "last_name": "Rodriguez",
    "age": 37,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 89000.0,
    "occupation": "Pharmacist"
  },
  {
    "email": "christopher.lewis@airline.com",
    "first_name": "Christopher",
    "last_name": "Lewis",
    "age": 40,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 102000.0,
    "occupation": "Pilot"
  },
  {
    "email": "ashley.walker@fashion.com",
    "first_name": "Ashley",
    "last_name": "Walker",
    "age": 24,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 48000.0,
    "occupation": "Fashion Designer"
  },
  {
    "email": "ethan.wilson@finance.net",
    "first_name": "Ethan",
    "last_name": "Wilson",
    "age": 28,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 82000.0,
    "occupation": "Investment Banker"
  },
  {
    "email": "chloe.clark@healthcare.org",
    "first_name": "Chloe",
    "last_name": "Clark",
    "age": 31,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Physician Assistant"
  },
  {
    "email": "benjamin.robinson@research.edu",
    "first_name": "Benjamin",
    "last_name": "Robinson",
    "age": 44,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Research Director"
  },
  {
    "email": "mia.lee@techstartup.io",
    "first_name": "Mia",
    "last_name": "Lee",
    "age": 27,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Product Manager"
  },
  {
    "email": "alexander.king@consulting.group",
    "first_name": "Alexander",
    "last_name": "King",
    "age": 36,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 135000.0,
    "occupation": "Senior Consultant"
  },
  {
    "email": "ava.scott@datascience.ai",
    "first_name": "Ava",
    "last_name": "Scott",
    "age": 25,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 88000.0,
    "occupation": "Machine Learning Engineer"
  },
  {
    "email": "samuel.wright@engineering.com",
    "first_name": "Samuel",
    "last_name": "Wright",
    "age": 39,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 112000.0,
    "occupation": "Civil Engineer"
  },
  {
    "email": "grace.young@medical.org",
    "first_name": "Grace",
    "last_name": "Young",
    "age": 34,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 115000.0,
    "occupation": "Anesthesiologist"
  },
  {
    "email": "joseph.hall@legalpartners.com",
    "first_name": "Joseph",
    "last_name": "Hall",
    "age": 41,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 160000.0,
    "occupation": "Partner Lawyer"
  },
  {
    "email": "ella.allen@education.gov",
    "first_name": "Ella",
    "last_name": "Allen",
    "age": 46,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 72000.0,
    "occupation": "School Principal"
  },
  {
    "email": "henry.green@autoindustry.com",
    "first_name": "Henry",
    "last_name": "Green",
    "age": 33,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Automotive Engineer"
  },
  {
    "email": "lily.baker@advertising.com",
    "first_name": "Lily",
    "last_name": "Baker",
    "age": 29,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 67000.0,
    "occupation": "Creative Director"
  },
  {
    "email": "jackson.adams@strategy.com",
    "first_name": "Jackson",
    "last_name": "Adams",
    "age": 37,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 142000.0,
    "occupation": "Strategy Consultant"
  },
  {
    "email": "scarlett.nelson@realestate.com",
    "first_name": "Scarlett",
    "last_name": "Nelson",
    "age": 32,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 92000.0,
    "occupation": "Real Estate Broker"
  },
  {
    "email": "lucas.carter@biotech.com",
    "first_name": "Lucas",
    "last_name": "Carter",
    "age": 35,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 110000.0,
    "occupation": "Biotech Researcher"
  },
  {
    "email": "zoey.mitchell@community.org",
    "first_name": "Zoey",
    "last_name": "Mitchell",
    "age": 26,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 58000.0,
    "occupation": "Community Organizer"
  },
  {
    "email": "logan.perez@cloudtech.com",
    "first_name": "Logan",
    "last_name": "Perez",
    "age": 30,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 128000.0,
    "occupation": "Cloud Architect"
  },
  {
    "email": "hannah.roberts@pharmacy.org",
    "first_name": "Hannah",
    "last_name": "Roberts",
    "age": 38,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 96000.0,
    "occupation": "Clinical Pharmacist"
  },
  {
    "email": "ryan.turner@aviation.com",
    "first_name": "Ryan",
    "last_name": "Turner",
    "age": 42,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 118000.0,
    "occupation": "Commercial Pilot"
  },
  {
    "email": "victoria.phillips@design.co",
    "first_name": "Victoria",
    "last_name": "Phillips",
    "age": 25,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 55000.0,
    "occupation": "Interior Designer"
  },
  {
    "email": "carter.campbell@fintech.io",
    "first_name": "Carter",
    "last_name": "Campbell",
    "age": 29,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 95000.0,
    "occupation": "FinTech Analyst"
  },
  {
    "email": "zoe.parker@hospital.net",
    "first_name": "Zoe",
    "last_name": "Parker",
    "age": 32,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 108000.0,
    "occupation": "Emergency Doctor"
  },
  {
    "email": "gabriel.edwards@harvard.edu",
    "first_name": "Gabriel",
    "last_name": "Edwards",
    "age": 48,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 140000.0,
    "occupation": "Department Head"
  },
  {
    "email": "penelope.collins@uiux.design",
    "first_name": "Penelope",
    "last_name": "Collins",
    "age": 28,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 82000.0,
    "occupation": "UI Designer"
  },
  {
    "email": "jayden.stewart@wealth.com",
    "first_name": "Jayden",
    "last_name": "Stewart",
    "age": 37,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 155000.0,
    "occupation": "Wealth Manager"
  },
  {
    "email": "nora.morris@analytics.co",
    "first_name": "Nora",
    "last_name": "Morris",
    "age": 24,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 78000.0,
    "occupation": "Business Analyst"
  },
  {
    "email": "leo.rogers@builders.com",
    "first_name": "Leo",
    "last_name": "Rogers",
    "age": 43,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 98000.0,
    "occupation": "Project Manager"
  },
  {
    "email": "riley.reed@healthsystem.org",
    "first_name": "Riley",
    "last_name": "Reed",
    "age": 35,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Cardiologist"
  },
  {
    "email": "aiden.cook@lawfirm.com",
    "first_name": "Aiden",
    "last_name": "Cook",
    "age": 39,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 175000.0,
    "occupation": "Corporate Lawyer"
  },
  {
    "email": "layla.morgan@university.edu",
    "first_name": "Layla",
    "last_name": "Morgan",
    "age": 47,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 68000.0,
    "occupation": "Assistant Professor"
  },
  {
    "email": "mateo.bell@electric.com",
    "first_name": "Mateo",
    "last_name": "Bell",
    "age": 34,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 90000.0,
    "occupation": "Electrical Engineer"
  },
  {
    "email": "aurora.cooper@branding.com",
    "first_name": "Aurora",
    "last_name": "Cooper",
    "age": 30,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 72000.0,
    "occupation": "Brand Manager"
  },
  {
    "email": "dylan.richardson@mckinsey.com",
    "first_name": "Dylan",
    "last_name": "Richardson",
    "age": 38,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 165000.0,
    "occupation": "Partner Consultant"
  },
  {
    "email": "clara.wood@salesforce.com",
    "first_name": "Clara",
    "last_name": "Wood",
    "age": 33,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 88000.0,
    "occupation": "Sales Director"
  },
  {
    "email": "axel.price@genetics.com",
    "first_name": "Axel",
    "last_name": "Price",
    "age": 36,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Geneticist"
  },
  {
    "email": "stella.bennett@youth.org",
    "first_name": "Stella",
    "last_name": "Bennett",
    "age": 27,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 54000.0,
    "occupation": "Youth Counselor"
  },
  {
    "email": "jaxon.hughes@google.com",
    "first_name": "Jaxon",
    "last_name": "Hughes",
    "age": 31,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 135000.0,
    "occupation": "Site Reliability Engineer"
  },
  {
    "email": "luna.flores@medicalcenter.org",
    "first_name": "Luna",
    "last_name": "Flores",
    "age": 39,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 102000.0,
    "occupation": "Radiologist"
  },
  {
    "email": "ezra.washington@delta.com",
    "first_name": "Ezra",
    "last_name": "Washington",
    "age": 44,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Airline Captain"
  },
  {
    "email": "maya.butler@luxury.com",
    "first_name": "Maya",
    "last_name": "Butler",
    "age": 26,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 62000.0,
    "occupation": "Luxury Retail Manager"
  },
  {
    "email": "liam.foster@banking.com",
    "first_name": "Liam",
    "last_name": "Foster",
    "age": 30,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 92000.0,
    "occupation": "Risk Analyst"
  },
  {
    "email": "ellie.gonzalez@childrens.org",
    "first_name": "Ellie",
    "last_name": "Gonzalez",
    "age": 33,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 115000.0,
    "occupation": "Pediatrician"
  },
  {
    "email": "owen.bryant@mit.edu",
    "first_name": "Owen",
    "last_name": "Bryant",
    "age": 49,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Research Professor"
  },
  {
    "email": "aria.russell@apple.com",
    "first_name": "Aria",
    "last_name": "Russell",
    "age": 29,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 115000.0,
    "occupation": "iOS Developer"
  },
  {
    "email": "levi.griffin@hedgefund.com",
    "first_name": "Levi",
    "last_name": "Griffin",
    "age": 36,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 185000.0,
    "occupation": "Hedge Fund Manager"
  },
  {
    "email": "elena.diaz@dataviz.com",
    "first_name": "Elena",
    "last_name": "Diaz",
    "age": 25,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Data Visualization Specialist"
  },
  {
    "email": "silas.hayes@infrastructure.com",
    "first_name": "Silas",
    "last_name": "Hayes",
    "age": 40,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 105000.0,
    "occupation": "Infrastructure Engineer"
  },
  {
    "email": "nadia.porter@clinic.org",
    "first_name": "Nadia",
    "last_name": "Porter",
    "age": 36,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 135000.0,
    "occupation": "Surgeon"
  },
  {
    "email": "caleb.simmons@justice.gov",
    "first_name": "Caleb",
    "last_name": "Simmons",
    "age": 42,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 155000.0,
    "occupation": "Federal Prosecutor"
  },
  {
    "email": "rose.fisher@college.edu",
    "first_name": "Rose",
    "last_name": "Fisher",
    "age": 44,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 75000.0,
    "occupation": "College Professor"
  },
  {
    "email": "jonah.holland@ford.com",
    "first_name": "Jonah",
    "last_name": "Holland",
    "age": 32,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Automotive Designer"
  },
  {
    "email": "iris.gibson@coca-cola.com",
    "first_name": "Iris",
    "last_name": "Gibson",
    "age": 31,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 78000.0,
    "occupation": "Product Marketing Manager"
  },
  {
    "email": "theodore.weber@bain.com",
    "first_name": "Theodore",
    "last_name": "Weber",
    "age": 39,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 172000.0,
    "occupation": "Principal Consultant"
  },
  {
    "email": "lilith.mcdonald@tourism.com",
    "first_name": "Lilith",
    "last_name": "McDonald",
    "age": 34,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 82000.0,
    "occupation": "Tourism Director"
  },
  {
    "email": "asher.lane@vaccine.com",
    "first_name": "Asher",
    "last_name": "Lane",
    "age": 37,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 118000.0,
    "occupation": "Vaccine Researcher"
  },
  {
    "email": "ada.fletcher@environment.org",
    "first_name": "Ada",
    "last_name": "Fletcher",
    "age": 28,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 56000.0,
    "occupation": "Environmental Scientist"
  },
  {
    "email": "maxwell.schwartz@netflix.com",
    "first_name": "Maxwell",
    "last_name": "Schwartz",
    "age": 32,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Streaming Engineer"
  },
  {
    "email": "ruby.wagner@mayo.edu",
    "first_name": "Ruby",
    "last_name": "Wagner",
    "age": 41,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 110000.0,
    "occupation": "Oncologist"
  },
  {
    "email": "kai.snyder@united.com",
    "first_name": "Kai",
    "last_name": "Snyder",
    "age": 45,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 132000.0,
    "occupation": "Flight Instructor"
  },
  {
    "email": "freya.lambert@casino.com",
    "first_name": "Freya",
    "last_name": "Lambert",
    "age": 27,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 68000.0,
    "occupation": "Casino Manager"
  },
  {
    "email": "elias.mason@citi.com",
    "first_name": "Elias",
    "last_name": "Mason",
    "age": 29,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 102000.0,
    "occupation": "Investment Analyst"
  },
  {
    "email": "juliet.beck@kaiser.org",
    "first_name": "Juliet",
    "last_name": "Beck",
    "age": 34,
    "gender": "F",
    "city": "Los Angeles",
    "country": "USA",
    "income": 125000.0,
    "occupation": "Psychiatrist"
  },
  {
    "email": "arthur.newman@tufts.edu",
    "first_name": "Arthur",
    "last_name": "Newman",
    "age": 50,
    "gender": "M",
    "city": "Boston",
    "country": "USA",
    "income": 150000.0,
    "occupation": "Dean of Faculty"
  },
  {
    "email": "eden.lucas@adobe.com",
    "first_name": "Eden",
    "last_name": "Lucas",
    "age": 30,
    "gender": "F",
    "city": "San Francisco",
    "country": "USA",
    "income": 98000.0,
    "occupation": "Graphic Designer"
  },
  {
    "email": "roman.owens@trading.com",
    "first_name": "Roman",
    "last_name": "Owens",
    "age": 35,
    "gender": "M",
    "city": "Chicago",
    "country": "USA",
    "income": 195000.0,
    "occupation": "Quantitative Trader"
  },
  {
    "email": "alexis.patrick@ibm.com",
    "first_name": "Alexis",
    "last_name": "Patrick",
    "age": 26,
    "gender": "F",
    "city": "Austin",
    "country": "USA",
    "income": 92000.0,
    "occupation": "AI Engineer"
  },
  {
    "email": "tobias.payne@oilgas.com",
    "first_name": "Tobias",
    "last_name": "Payne",
    "age": 42,
    "gender": "M",
    "city": "Houston",
    "country": "USA",
    "income": 122000.0,
    "occupation": "Petroleum Engineer"
  },
  {
    "email": "camille.boone@mercy.org",
    "first_name": "Camille",
    "last_name": "Boone",
    "age": 37,
    "gender": "F",
    "city": "Philadelphia",
    "country": "USA",
    "income": 145000.0,
    "occupation": "Neurologist"
  },
  {
    "email": "spencer.barry@supremecourt.gov",
    "first_name": "Spencer",
    "last_name": "Barry",
    "age": 47,
    "gender": "M",
    "city": "Washington DC",
    "country": "USA",
    "income": 190000.0,
    "occupation": "Constitutional Lawyer"
  },
  {
    "email": "lydia.ball@k12.edu",
    "first_name": "Lydia",
    "last_name": "Ball",
    "age": 39,
    "gender": "F",
    "city": "Seattle",
    "country": "USA",
    "income": 82000.0,
    "occupation": "Special Education Teacher"
  },
  {
    "email": "brody.logan@tesla.com",
    "first_name": "Brody",
    "last_name": "Logan",
    "age": 33,
    "gender": "M",
    "city": "Detroit",
    "country": "USA",
    "income": 115000.0,
    "occupation": "EV Engineer"
  },
  {
    "email": "savannah.owens@nike.com",
    "first_name": "Savannah",
    "last_name": "Owens",
    "age": 32,
    "gender": "F",
    "city": "Atlanta",
    "country": "USA",
    "income": 85000.0,
    "occupation": "Sports Marketing Manager"
  },
  {
    "email": "jude.curtis@ey.com",
    "first_name": "Jude",
    "last_name": "Curtis",
    "age": 40,
    "gender": "M",
    "city": "Dallas",
    "country": "USA",
    "income": 168000.0,
    "occupation": "Audit Partner"
  },
  {
    "email": "delilah.harvey@marriott.com",
    "first_name": "Delilah",
    "last_name": "Harvey",
    "age": 35,
    "gender": "F",
    "city": "Miami",
    "country": "USA",
    "income": 95000.0,
    "occupation": "Hotel General Manager"
  },
  {
    "email": "bennett.wade@pfizer.com",
    "first_name": "Bennett",
    "last_name": "Wade",
    "age": 38,
    "gender": "M",
    "city": "San Diego",
    "country": "USA",
    "income": 128000.0,
    "occupation": "Clinical Trial Manager"
  },
  {
    "email": "remi.day@wildlife.org",
    "first_name": "Remi",
    "last_name": "Day",
    "age": 29,
    "gender": "F",
    "city": "Portland",
    "country": "USA",
    "income": 59000.0,
    "occupation": "Wildlife Biologist"
  },
  {
    "email": "finn.cobb@nvidia.com",
    "first_name": "Finn",
    "last_name": "Cobb",
    "age": 31,
    "gender": "M",
    "city": "San Jose",
    "country": "USA",
    "income": 155000.0,
    "occupation": "GPU Architect"
  },
  {
    "email": "cora.brewer@clevelandclinic.org",
    "first_name": "Cora",
    "last_name": "Brewer",
    "age": 43,
    "gender": "F",
    "city": "Phoenix",
    "country": "USA",
    "income": 118000.0,
    "occupation": "Cardiac Surgeon"
  },
  {
    "email": "kellen.leonard@southwest.com",
    "first_name": "Kellen",
    "last_name": "Leonard",
    "age": 46,
    "gender": "M",
    "city": "Denver",
    "country": "USA",
    "income": 138000.0,
    "occupation": "Chief Pilot"
  },
  {
    "email": "jolie.todd@eventplanning.com",
    "first_name": "Jolie",
    "last_name": "Todd",
    "age": 28,
    "gender": "F",
    "city": "Las Vegas",
    "country": "USA",
    "income": 71000.0,
    "occupation": "Event Planner"
  },
  {
    "email": "dash.blair@morganstanley.com",
    "first_name": "Dash",
    "last_name": "Blair",
    "age": 30,
    "gender": "M",
    "city": "New York",
    "country": "USA",
    "income": 112000.0,
    "occupation": "Portfolio Manager"
  }
]


print(f"✅ Loaded {len(users_data)} users for chatbot training")

def create_pattern_based_training_data(users_data):
    """Create training data that teaches PATTERNS, not memorization"""
    training_pairs = []

    # PHASE 1: TEACH PATTERNS WITHOUT USER DATA
    # These patterns will be used to generate responses dynamically

    # Pattern 1: Greeting patterns
    greeting_patterns = [
        ("hello", "Hello! How can I help you?"),
        ("hi", "Hi there! What can I do for you?"),
        ("hey", "Hey! How can I assist?"),
        ("greetings", "Greetings! I'm here to help."),
    ]
    training_pairs.extend(greeting_patterns)

    # Pattern 2: Help patterns
    help_patterns = [
        ("help", "I can help with user profiles. Ask about occupations, locations, ages, or incomes."),
        ("what can you do", "I can answer questions about user profiles and personal information."),
        ("commands", "Try: 'my occupation', 'my location', 'my age', 'my income', 'my name'"),
    ]
    training_pairs.extend(help_patterns)

    # Pattern 3: Goodbye patterns
    goodbye_patterns = [
        ("bye", "Goodbye! Have a great day."),
        ("exit", "Thanks for chatting!"),
        ("quit", "Bye! Come back anytime."),
    ]
    training_pairs.extend(goodbye_patterns)

    # Pattern 4: Thanks patterns
    thanks_patterns = [
        ("thank you", "You're welcome!"),
        ("thanks", "My pleasure!"),
    ]
    training_pairs.extend(thanks_patterns)

    # PHASE 2: TEACH RESPONSE TEMPLATES (WITH PLACEHOLDERS)
    # The model will learn to fill in placeholders with actual data

    # Occupation patterns
    occupation_patterns = [
        ("what is my occupation", "Your occupation is [OCCUPATION]."),
        ("what do i do", "You work as a [OCCUPATION]."),
        ("my job", "Your job is [OCCUPATION]."),
        ("what's my profession", "You are a [OCCUPATION]."),
        ("what is my work", "You work as a [OCCUPATION]."),
    ]

    # Location patterns
    location_patterns = [
        ("where do i live", "You live in [CITY], [COUNTRY]."),
        ("my location", "Your location is [CITY]."),
        ("where am i from", "You are from [CITY], [COUNTRY]."),
        ("what city am i in", "You are in [CITY]."),
    ]

    # Age patterns
    age_patterns = [
        ("how old am i", "You are [AGE] years old."),
        ("my age", "Your age is [AGE]."),
        ("what is my age", "You are [AGE] years old."),
        ("age please", "Age: [AGE] years."),
    ]

    # Income patterns
    income_patterns = [
        ("what is my income", "Your income is $[INCOME] per year."),
        ("my salary", "You earn $[INCOME] annually."),
        ("how much do i earn", "Your annual income is $[INCOME]."),
        ("what's my income", "Income: $[INCOME] per year."),
    ]

    # Name patterns
    name_patterns = [
        ("what's my name", "Your name is [FIRST_NAME] [LAST_NAME]."),
        ("my name", "You are [FIRST_NAME] [LAST_NAME]."),
        ("what is my name", "Name: [FIRST_NAME] [LAST_NAME]."),
        ("tell me my name", "Your name is [FIRST_NAME]."),
    ]

    # Profile patterns
    profile_patterns = [
        ("tell me about myself", "You are [FIRST_NAME], a [AGE]-year-old [OCCUPATION] from [CITY]."),
        ("my profile", "[FIRST_NAME] [LAST_NAME]: [AGE] years old, [OCCUPATION] in [CITY]."),
        ("who am i", "You're [FIRST_NAME] [LAST_NAME], a [OCCUPATION] from [CITY]."),
        ("about me", "[FIRST_NAME] is [AGE] years old and works as a [OCCUPATION] in [CITY]."),
    ]

    # Combine all patterns
    all_patterns = (occupation_patterns + location_patterns + age_patterns +
                   income_patterns + name_patterns + profile_patterns)

    # Add patterns to training data
    training_pairs.extend(all_patterns)

    # PHASE 3: TEACH THE MODEL TO HANDLE PLACEHOLDERS
    # Create examples with filled placeholders
    placeholder_examples = []

    # Sample some users to create examples
    sample_users = users_data[:10]  # Use first 10 users as examples

    for user in sample_users:
        # Fill occupation patterns
        for pattern in occupation_patterns:
            question, template = pattern
            response = template.replace("[OCCUPATION]", user['occupation'].lower())
            placeholder_examples.append((question, response))

        # Fill location patterns
        for pattern in location_patterns:
            question, template = pattern
            response = template.replace("[CITY]", user['city'])
            response = response.replace("[COUNTRY]", user['country'])
            placeholder_examples.append((question, response))

        # Fill age patterns
        for pattern in age_patterns:
            question, template = pattern
            response = template.replace("[AGE]", str(user['age']))
            placeholder_examples.append((question, response))

        # Fill income patterns
        for pattern in income_patterns:
            question, template = pattern
            response = template.replace("[INCOME]", f"{user['income']:,}")
            placeholder_examples.append((question, response))

        # Fill name patterns
        for pattern in name_patterns:
            question, template = pattern
            response = template.replace("[FIRST_NAME]", user['first_name'])
            response = response.replace("[LAST_NAME]", user['last_name'])
            placeholder_examples.append((question, response))

        # Fill profile patterns
        for pattern in profile_patterns:
            question, template = pattern
            response = template.replace("[FIRST_NAME]", user['first_name'])
            response = response.replace("[LAST_NAME]", user['last_name'])
            response = response.replace("[AGE]", str(user['age']))
            response = response.replace("[OCCUPATION]", user['occupation'].lower())
            response = response.replace("[CITY]", user['city'])
            placeholder_examples.append((question, response))

    # Add placeholder examples to training data
    training_pairs.extend(placeholder_examples)

    # PHASE 4: Add some randomness to prevent memorization
    random_patterns = [
        ("what else", "Try asking about your occupation or location."),
        ("ok", "Alright, what would you like to know?"),
        ("i see", "Great! What else can I help with?"),
        ("maybe", "Let me know if you have any questions."),
        ("hmm", "Is there something specific you'd like to know?"),
    ]
    training_pairs.extend(random_patterns)

    # Shuffle to prevent order memorization
    random.shuffle(training_pairs)

    return training_pairs

# Create pattern-based training data
training_pairs = create_pattern_based_training_data(users_data)
print(f"✅ Created {len(training_pairs)} pattern-based training pairs")

print("\n📋 Sample training pairs (showing patterns):")
print("-" * 50)
for i in range(5):
    print(f"  User: '{training_pairs[i][0]}'")
    print(f"  Bot:  '{training_pairs[i][1]}'")
    print()

print("\n" + "="*60)
print("PREPARING DATA FOR MODEL TRAINING")
print("="*60)

# Prepare data
inputs = [pair[0] for pair in training_pairs]
outputs = [pair[1] for pair in training_pairs]

print(f"Total training examples: {len(inputs)}")

# Create tokenizers
input_tokenizer = Tokenizer(oov_token="<OOV>", filters='')
input_tokenizer.fit_on_texts(inputs)
input_sequences = input_tokenizer.texts_to_sequences(inputs)
max_input_len = max(len(seq) for seq in input_sequences)
input_padded = pad_sequences(input_sequences, maxlen=max_input_len, padding='post')

output_tokenizer = Tokenizer(oov_token="<OOV>", filters='')
output_tokenizer.fit_on_texts(outputs)
output_sequences = output_tokenizer.texts_to_sequences(outputs)
max_output_len = max(len(seq) for seq in output_sequences)
output_padded = pad_sequences(output_sequences, maxlen=max_output_len, padding='post')

print(f"📊 Data shapes:")
print(f"   Input shape: {input_padded.shape}")
print(f"   Output shape: {output_padded.shape}")
print(f"   Max input length: {max_input_len}")
print(f"   Max output length: {max_output_len}")

print("\n" + "="*60)
print("BUILDING SIMPLER MODEL (TO LEARN PATTERNS, NOT MEMORIZE)")
print("="*60)

# Build a simpler model focused on learning patterns
vocab_size = len(output_tokenizer.word_index) + 1

# Simple encoder
encoder_inputs = Input(shape=(max_input_len,))
encoder_embedding = Embedding(len(input_tokenizer.word_index) + 1, 128)(encoder_inputs)
encoder_lstm = LSTM(128, return_state=True, dropout=0.2)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_embedding)
encoder_states = [state_h, state_c]

# Simple decoder
decoder_inputs = Input(shape=(max_output_len,))
decoder_embedding = Embedding(vocab_size, 128)(decoder_inputs)
decoder_lstm = LSTM(128, return_sequences=True, return_state=True, dropout=0.2)
decoder_outputs, _, _ = decoder_lstm(decoder_embedding, initial_state=encoder_states)
decoder_dense = Dense(vocab_size, activation='softmax')
decoder_outputs = decoder_dense(decoder_outputs)

# Build model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model Summary:")
model.summary()

print("\n" + "="*60)
print("TRAINING MODEL TO LEARN PATTERNS")
print("="*60)

# Prepare decoder data
decoder_input_data = np.zeros_like(output_padded)
decoder_input_data[:, 1:] = output_padded[:, :-1]
decoder_input_data[:, 0] = output_tokenizer.word_index['<OOV>']
decoder_target_data = np.expand_dims(output_padded, -1)

# Train with early stopping to prevent overfitting
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    [input_padded, decoder_input_data],
    decoder_target_data,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping],
    verbose=1
)

print("\n" + "="*60)
print("BUILDING INFERENCE MODELS")
print("="*60)

# Encoder inference model
encoder_model = Model(encoder_inputs, encoder_states)

# Decoder inference model
decoder_state_input_h = Input(shape=(128,))
decoder_state_input_c = Input(shape=(128,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]

decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_embedding, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)

decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

print("✅ Inference models built")

print("\n" + "="*60)
print("CREATING RESPONSE GENERATOR WITH DYNAMIC DATA")
print("="*60)

def decode_sequence_simple(input_seq):
    """Simple greedy decoding for pattern-based model"""
    states_value = encoder_model.predict(input_seq, verbose=0)

    target_seq = np.zeros((1, 1))
    target_seq[0, 0] = output_tokenizer.word_index['<OOV>']

    decoded_sentence = ''
    max_decoded_len = 30

    for _ in range(max_decoded_len):
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value, verbose=0)

        # Greedy decoding
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_word = None

        for word, index in output_tokenizer.word_index.items():
            if index == sampled_token_index:
                sampled_word = word
                break

        if sampled_word is None or sampled_word == '<OOV>':
            break

        decoded_sentence += ' ' + sampled_word

        # Stop if we predict end of sentence
        if sampled_word in ['.', '!', '?'] and len(decoded_sentence) > 10:
            break

        # Update
        target_seq = np.zeros((1, 1))
        target_seq[0, 0] = sampled_token_index
        states_value = [h, c]

    return decoded_sentence.strip()

def generate_response_with_data(user_input, user_data=None):
    """
    Generate response by:
    1. Handling greetings/help/bye
    2. Filling placeholders from pattern-based response
    3. Using intent-based fallback if placeholders missing
    """
    # Lowercase input for uniformity
    user_input_lower = user_input.lower().strip()

    # ---- 1. Handle special cases ----
    greetings = ["hello", "hi", "hey"]
    farewells = ["bye", "goodbye", "see you"]
    help_inputs = ["help", "what can you do", "commands"]

    if user_input_lower in greetings:
        return "Hello! How can I assist you today?"
    if user_input_lower in farewells:
        return "Goodbye! Have a great day!"
    if user_input_lower in help_inputs:
        return "I can tell you about yourself: your age, occupation, income, and location."

    # ---- 2. Pattern-based response ----
    input_seq = input_tokenizer.texts_to_sequences([user_input_lower])
    input_padded_seq = pad_sequences(input_seq, maxlen=max_input_len, padding='post')
    pattern_response = decode_sequence_simple(input_padded_seq) or ""

    if user_data is None:
        return pattern_response or "I can help with user profiles."

    # Fill placeholders
    placeholders = {
        "[FIRST_NAME]": user_data['first_name'],
        "[LAST_NAME]": user_data['last_name'],
        "[AGE]": str(user_data['age']),
        "[OCCUPATION]": user_data['occupation'].lower(),
        "[CITY]": user_data['city'],
        "[COUNTRY]": user_data['country'],
        "[INCOME]": f"{user_data['income']:,}"
    }

    for ph, val in placeholders.items():
        pattern_response = pattern_response.replace(ph, val)

    # ---- 3. Intent-based fallback if placeholders remain ----
    if any(ph in pattern_response for ph in placeholders):
        if "occupation" in user_input_lower:
            return f"You work as a {user_data['occupation'].lower()}."
        elif any(x in user_input_lower for x in ["live", "city", "location", "where"]):
            return f"You live in {user_data['city']}, {user_data['country']}."
        elif "age" in user_input_lower:
            return f"You are {user_data['age']} years old."
        elif any(x in user_input_lower for x in ["income", "salary", "earn"]):
            return f"Your income is ${user_data['income']:,} per year."
        elif "name" in user_input_lower:
            return f"Your name is {user_data['first_name']} {user_data['last_name']}."
        elif "tell me about myself" in user_input_lower:
            return (f"You are {user_data['first_name']} {user_data['last_name']}, "
                    f"a {user_data['age']}-year-old {user_data['occupation'].lower()} "
                    f"from {user_data['city']}, {user_data['country']}.")
        else:
            return f"You are {user_data['first_name']}, a {user_data['age']}-year-old {user_data['occupation'].lower()} from {user_data['city']}."

    return pattern_response

print("\n" + "="*60)
print("TESTING PATTERN-BASED CHATBOT")
print("="*60)

# Test with sample user
test_user = users_data[0]  # John Smith

test_cases = [
    ("hello", None),  # No user data needed for greetings
    ("what is my occupation", test_user),
    ("where do i live", test_user),
    ("how old am i", test_user),
    ("what is my income", test_user),
    ("what's my name", test_user),
    ("tell me about myself", test_user),
    ("help", None),
    ("bye", None),
]

print("🤖 Testing with user: John Smith")
print("-" * 50)

for user_input, user_data in test_cases:
    response = generate_response_with_data(user_input, user_data)
    print(f"👤 User: {user_input}")
    print(f"🤖 Bot: {response}")
    print()

print("\n" + "="*60)
print("SAVING FILES FOR DJANGO INTEGRATION")
print("="*60)

# Save all necessary files
model.save('pattern_based_model.h5')
encoder_model.save('pattern_encoder.h5')
decoder_model.save('pattern_decoder.h5')

with open('input_tokenizer_pattern.pkl', 'wb') as f:
    pickle.dump(input_tokenizer, f)

with open('output_tokenizer_pattern.pkl', 'wb') as f:
    pickle.dump(output_tokenizer, f)

with open('pattern_config.pkl', 'wb') as f:
    config = {
        'max_input_len': max_input_len,
        'max_output_len': max_output_len,
        'vocab_size': vocab_size
    }
    pickle.dump(config, f)

# Save the training patterns for reference
patterns_to_save = {
    'occupation_patterns': [
        ("what is my occupation", "Your occupation is [OCCUPATION]."),
        ("what do i do", "You work as a [OCCUPATION]."),
    ],
    'location_patterns': [
        ("where do i live", "You live in [CITY], [COUNTRY]."),
        ("my location", "Your location is [CITY]."),
    ],
    'age_patterns': [
        ("how old am i", "You are [AGE] years old."),
        ("my age", "Your age is [AGE]."),
    ],
    'income_patterns': [
        ("what is my income", "Your income is $[INCOME] per year."),
        ("my salary", "You earn $[INCOME] annually."),
    ],
    'name_patterns': [
        ("what's my name", "Your name is [FIRST_NAME] [LAST_NAME]."),
        ("my name", "You are [FIRST_NAME] [LAST_NAME]."),
    ],
    'profile_patterns': [
        ("tell me about myself", "You are [FIRST_NAME], a [AGE]-year-old [OCCUPATION] from [CITY]."),
        ("my profile", "[FIRST_NAME] [LAST_NAME]: [AGE] years old, [OCCUPATION] in [CITY]."),
    ],
}

with open('response_patterns.pkl', 'wb') as f:
    pickle.dump(patterns_to_save, f)

print("✅ Files saved successfully!")
print("\n📁 Files to download:")
print("   1. pattern_based_model.h5")
print("   2. pattern_encoder.h5")
print("   3. pattern_decoder.h5")
print("   4. input_tokenizer_pattern.pkl")
print("   5. output_tokenizer_pattern.pkl")
print("   6. pattern_config.pkl")
print("   7. response_patterns.pkl")

print("\n" + "="*60)
print("HOW TO USE IN DJANGO:")
print("="*60)
print("""
1. Copy all 7 files to your Django project
2. In your Django view:

   def get_chatbot_response(user_input, user_data):
       # 1. Load models and tokenizers
       # 2. Use generate_response_with_data() function
       # 3. Pass user_input and user_data (from your database)

3. The model learns PATTERNS, not specific users
4. User data is injected at response time
""")

print("\n✅ This model learns patterns like:")
print("   'what is my occupation' -> 'Your occupation is [OCCUPATION].'")
print("   Then fills [OCCUPATION] with actual data at runtime!")

# def get_context_based_response(user_input, user_context=None):
#     """Get response with context awareness"""
#     # Preprocess input
#     input_seq = input_tokenizer.texts_to_sequences([user_input.lower()])
#     input_padded_seq = pad_sequences(input_seq, maxlen=max_input_len, padding='post')

#     # Generate response
#     response = decode_sequence_v2(input_padded_seq)

#     # If response is empty or generic, provide fallback
#     if not response or len(response) < 5:
#         # Common fallback responses
#         fallbacks = [
#             "I'm not sure I understand. Could you rephrase your question?",
#             "I specialize in user profile information. Try asking about occupations, ages, or locations.",
#             "Could you ask that differently? I'm here to help with user information.",
#             "I didn't catch that. You can ask me about user profiles or personal information.",
#         ]
#         import random
#         response = random.choice(fallbacks)

#     return response

# # Test with various inputs
# print("🤖 Chatbot Testing - Improved Version:")
# print("-" * 50)

# test_inputs = [
#     "hello",
#     "hi there",
#     "what can you do?",
#     "help",
#     "tell me about myself",
#     "what is my occupation",
#     "where do i live",
#     "how old am i",
#     "what is my income",
#     "thank you",
#     "bye",
#     "who created you",
#     "what's your name",
# ]

# for test_input in test_inputs:
#     response = get_context_based_response(test_input)
#     print(f"👤 User: {test_input}")
#     print(f"🤖 Bot: {response}")
#     print()

# print("\n" + "="*60)
# print("SAVING IMPROVED MODEL")
# print("="*60)

# # Save all components
# model.save('improved_chatbot_model.h5')
# encoder_model.save('improved_encoder_model.h5')
# decoder_model.save('improved_decoder_model.h5')

# with open('improved_input_tokenizer.pkl', 'wb') as f:
#     pickle.dump(input_tokenizer, f)

# with open('improved_output_tokenizer.pkl', 'wb') as f:
#     pickle.dump(output_tokenizer, f)

# with open('improved_config.pkl', 'wb') as f:
#     config = {
#         'max_input_len': max_input_len,
#         'max_output_len': max_output_len,
#         'vocab_size': vocab_size
#     }
#     pickle.dump(config, f)

# print("✅ Improved models and tokenizers saved successfully!")

# print("\n" + "="*60)
# print("INTERACTIVE CHATBOT")
# print("="*60)

# def interactive_chat():
#     """Interactive chat session"""
#     print("🤖 Chatbot is ready! Type 'exit' to end the chat.")
#     print("-" * 50)

#     while True:
#         user_input = input("\n👤 You: ").strip()

#         if user_input.lower() in ['exit', 'quit', 'bye', 'goodbye']:
#             print("🤖 Bot: Goodbye! Thanks for chatting!")
#             break

#         if user_input:
#             response = get_context_based_response(user_input)
#             print(f"🤖 Bot: {response}")
#         else:
#             print("🤖 Bot: Please type something!")

# # Uncomment to run interactive chat
# # interactive_chat()





"""Convert data into stringfy into key pair values."""