# Generated by Django 5.2.7 on 2025-10-31 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
