# Generated by Django 5.2.7 on 2025-11-03 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_table_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('meat', 'Meat'), ('seafood', 'Seafood'), ('dairy', 'Dairy'), ('grains', 'Grains'), ('spices', 'Spices'), ('beverages', 'Beverages'), ('cleaning', 'Cleaning Supplies'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can')], max_length=10),
        ),
    ]
