# Generated by Django 5.2.7 on 2025-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
